"""新增 toprankmovies 資料表

Revision ID: 54b354ca7308
Revises: 
Create Date: 2021-11-20 00:11:34.417974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54b354ca7308'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('toprankmovies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.Column('imdb_id', sa.String(length=15), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('insert_datetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('imdb_id')
    )
    op.create_index(op.f('ix_toprankmovies_tmdb_id'), 'toprankmovies', ['tmdb_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_toprankmovies_tmdb_id'), table_name='toprankmovies')
    op.drop_table('toprankmovies')
    # ### end Alembic commands ###
