"""新增 users 表欄位

Revision ID: a56cc4abb246
Revises: 4915749f7f7e
Create Date: 2021-11-27 00:11:14.555610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a56cc4abb246'
down_revision = '4915749f7f7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('favorite_movie_genres', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'favorite_movie_genres')
    # ### end Alembic commands ###
